title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
remote_theme: just-the-docs/just-the-docs
search_enabled: false
just_the_docs:
  custom_css:
    - assets/css/custom.css
url: https://just-the-docs.github.io
