title: PVP Academy
description: 
remote_theme: just-the-docs/just-the-docs
search_enabled: false
just_the_docs:
  toc_enabled: false

footer_content: ""
back_to_top: false

url: "https://dforasti88.github.io"
baseurl: "/pvpacademy"
